language: ruby

rvm:
 - 2.4.9
 - 2.5.7
 - 2.6.5
 - 2.7.0
 - ruby-head
 - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile

sudo: false

script:
  - gem install bundler
  - bundle exec rspec
  - bundle exec rubocop
