language: ruby

rvm:
 - 2.4.9
 - 2.5.7
 - 2.6.5
 - 2.7.0
 - ruby-head
 - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

gemfile:
  - Gemfile

sudo: false

before_install:
  - gem update --system
  - gem update bundler

script:
  - bundle exec rspec
  - bundle exec rubocop
